-- Инициализация источника: схема shop, роли, публикация под CDC.
-- Выполняется entrypoint-ом образа postgres при первом старте на пустом томе
-- (psql -v ON_ERROR_STOP=1 --dbname source). Скрипт идемпотентный:
-- его можно прогнать повторно руками, ничего не упадет и не задублируется.
--
-- Пароли ролей берутся из переменных окружения контейнера source-db.

\getenv cdc_password CDC_USER_PASSWORD
\getenv app_password APP_USER_PASSWORD

-- ---------------------------------------------------------------------------
-- Роли
-- ---------------------------------------------------------------------------

-- cdc_user: чтение + репликация, под коннектор (Debezium и т.п.)
SELECT format('CREATE ROLE cdc_user WITH LOGIN REPLICATION PASSWORD %L', :'cdc_password')
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'cdc_user')
\gexec
-- на случай, если роль уже была, но с другими атрибутами/паролем
SELECT format('ALTER ROLE cdc_user WITH LOGIN REPLICATION PASSWORD %L', :'cdc_password')
\gexec

-- shop_app: прикладная роль генератора, без репликации
SELECT format('CREATE ROLE shop_app WITH LOGIN PASSWORD %L', :'app_password')
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'shop_app')
\gexec
SELECT format('ALTER ROLE shop_app WITH LOGIN NOREPLICATION PASSWORD %L', :'app_password')
\gexec

-- ---------------------------------------------------------------------------
-- Схема и таблицы
-- ---------------------------------------------------------------------------

CREATE SCHEMA IF NOT EXISTS shop;

CREATE TABLE IF NOT EXISTS shop.customers (
    customer_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name   text        NOT NULL,
    city        text        NOT NULL,
    segment     text        NOT NULL CHECK (segment IN ('retail', 'b2b', 'vip')),
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS shop.delivery_points (
    point_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       text          NOT NULL,
    city       text          NOT NULL,
    address    text          NOT NULL,
    lat        numeric(9, 6) NOT NULL,
    lon        numeric(9, 6) NOT NULL,
    point_type text          NOT NULL CHECK (point_type IN ('pickup', 'locker', 'courier_zone')),
    created_at timestamptz   NOT NULL DEFAULT now(),
    updated_at timestamptz   NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS shop.orders (
    order_id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id         bigint         NOT NULL REFERENCES shop.customers (customer_id),
    point_id            bigint         NOT NULL REFERENCES shop.delivery_points (point_id),
    status              text           NOT NULL
        CHECK (status IN ('created', 'assembling', 'in_delivery', 'delivered', 'cancelled')),
    total_amount        numeric(12, 2) NOT NULL,
    items_count         int            NOT NULL,
    is_cancelled        boolean        NOT NULL DEFAULT false,
    created_at          timestamptz    NOT NULL DEFAULT now(),
    updated_at          timestamptz    NOT NULL DEFAULT now(),
    planned_delivery_at timestamptz,
    actual_delivery_at  timestamptz    -- null, пока заказ не доставлен
);

-- по updated_at пойдет инкрементальная выгрузка
CREATE INDEX IF NOT EXISTS customers_updated_at_idx       ON shop.customers (updated_at);
CREATE INDEX IF NOT EXISTS delivery_points_updated_at_idx ON shop.delivery_points (updated_at);
CREATE INDEX IF NOT EXISTS orders_updated_at_idx          ON shop.orders (updated_at);

-- служебные индексы генератора: удаление клиента с заказами и выбор активных заказов
CREATE INDEX IF NOT EXISTS orders_customer_id_idx ON shop.orders (customer_id);
CREATE INDEX IF NOT EXISTS orders_point_id_idx    ON shop.orders (point_id);
CREATE INDEX IF NOT EXISTS orders_status_idx      ON shop.orders (status);

-- в событиях UPDATE/DELETE должны приезжать прежние значения всех колонок
ALTER TABLE shop.customers       REPLICA IDENTITY FULL;
ALTER TABLE shop.delivery_points REPLICA IDENTITY FULL;
ALTER TABLE shop.orders          REPLICA IDENTITY FULL;

-- ---------------------------------------------------------------------------
-- Права
-- ---------------------------------------------------------------------------

GRANT CONNECT ON DATABASE source TO cdc_user, shop_app;
GRANT USAGE ON SCHEMA shop TO cdc_user, shop_app;

GRANT SELECT ON ALL TABLES IN SCHEMA shop TO cdc_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA shop TO shop_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA shop TO shop_app;

-- генератор следит за размером тома и считает WAL через pg_ls_waldir(),
-- по умолчанию она доступна только суперпользователю
GRANT EXECUTE ON FUNCTION pg_catalog.pg_ls_waldir() TO shop_app;

-- для таблиц, которые появятся в схеме позже
ALTER DEFAULT PRIVILEGES IN SCHEMA shop GRANT SELECT ON TABLES TO cdc_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA shop GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO shop_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA shop GRANT USAGE, SELECT ON SEQUENCES TO shop_app;

-- ---------------------------------------------------------------------------
-- Публикация (слот репликации не создаем, его создаст коннектор)
-- ---------------------------------------------------------------------------

SELECT 'CREATE PUBLICATION shop_pub FOR TABLE shop.customers, shop.delivery_points, shop.orders'
WHERE NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'shop_pub')
\gexec
-- если публикация уже была с другим набором таблиц, приводим к нужному
ALTER PUBLICATION shop_pub SET TABLE shop.customers, shop.delivery_points, shop.orders;
